export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          avatar_url: string | null;
          role: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          slug: string;
          owner_id: string;
          plan: string;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["workspaces"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["workspaces"]["Insert"]>;
      };
      workspace_members: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          role: "owner" | "admin" | "member" | "viewer";
          joined_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["workspace_members"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["workspace_members"]["Insert"]>;
      };
      people: {
        Row: {
          id: string;
          workspace_id: string;
          name_en: string;
          name_ar: string | null;
          email: string | null;
          phone: string | null;
          role_en: string | null;
          role_ar: string | null;
          organization_id: string | null;
          avatar_url: string | null;
          type?: string;
          status?: string;
          tags: string[];
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["people"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["people"]["Insert"]>;
      };
      organizations: {
        Row: {
          id: string;
          workspace_id: string;
          name_en: string;
          name_ar: string | null;
          sector: string | null;
          lifecycle: string | null;
          health_score: number;
          headcount: number | null;
          website: string | null;
          type?: string;
          status?: string;
          industry?: string;
          phone?: string | null;
          email?: string | null;
          tags: string[];
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["organizations"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["organizations"]["Insert"]>;
      };
      work_items: {
        Row: {
          id: string;
          workspace_id: string;
          title_en: string;
          title_ar: string | null;
          type: "task" | "project" | "milestone" | "action" | "initiative" | "ticket" | "request" | "purchase_request" | "purchase_order" | "production_order" | "stock_movement" | "maintenance" | "quotation" | "sales_order";
          status: "backlog" | "planned" | "todo" | "in_progress" | "review" | "done" | "blocked" | "cancelled" | "draft" | "submitted" | "approved" | "rejected" | "ordered" | "sent" | "partially_received" | "received" | "expired" | "converted";
          priority: "critical" | "urgent" | "high" | "medium" | "low";
          assignee_id: string | null;
          parent_id: string | null;
          organization_id: string | null;
          due_date: string | null;
          progress: number;
          total_amount?: number;
          title?: string;
          tags: string[];
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["work_items"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["work_items"]["Insert"]>;
      };
      deals: {
        Row: {
          id: string;
          workspace_id: string;
          title_en: string;
          title_ar: string | null;
          value: number;
          currency: string;
          stage: string;
          probability: number;
          org_name_en: string | null;
          org_name_ar: string | null;
          contact_name_en: string | null;
          contact_name_ar: string | null;
          organization_id: string | null;
          expected_close_date: string | null;
          tags: string[];
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["deals"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["deals"]["Insert"]>;
      };
      invoices: {
        Row: {
          id: string;
          workspace_id: string;
          number: string;
          org_name_en: string;
          org_name_ar: string | null;
          organization_id: string | null;
          deal_id: string | null;
          amount: number;
          currency: string;
          status: string;
          due_date: string | null;
          paid_date: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["invoices"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["invoices"]["Insert"]>;
      };
      payments: {
        Row: {
          id: string;
          workspace_id: string;
          invoice_id: string | null;
          amount: number;
          currency: string;
          method: string | null;
          status: string;
          paid_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["payments"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["payments"]["Insert"]>;
      };
      expenses: {
        Row: {
          id: string;
          workspace_id: string;
          description_en: string;
          description_ar: string | null;
          amount: number;
          currency: string;
          category: string | null;
          date: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["expenses"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["expenses"]["Insert"]>;
      };
      resources: {
        Row: {
          id: string;
          workspace_id: string;
          name_en: string;
          name_ar: string | null;
          type: string;
          utilization: number;
          department: string | null;
          skills: string[];
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["resources"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["resources"]["Insert"]>;
      };
      activity_events: {
        Row: {
          id: string;
          workspace_id: string;
          actor_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string;
          description_en: string | null;
          description_ar: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["activity_events"]["Row"], "id" | "created_at">;
        Update: never;
      };
      site_visits: {
        Row: {
          id: string;
          workspace_id: string;
          visit_number: string;
          sales_order_id: string | null;
          customer_id: string | null;
          customer_name: string | null;
          site_address: string | null;
          assigned_technician: string | null;
          visit_date: string | null;
          status: "scheduled" | "in_progress" | "completed" | "cancelled";
          notes: string | null;
          preferred_colors: string | null;
          preferred_materials: string | null;
          preferred_style: "modern" | "classic" | "minimal" | "luxury" | "custom" | null;
          special_notes: string | null;
          installation_notes: string | null;
          checklist: Json;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["site_visits"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["site_visits"]["Insert"]>;
      };
      measurements: {
        Row: {
          id: string;
          workspace_id: string;
          site_visit_id: string;
          room_name: string;
          room_type: "kitchen" | "bedroom" | "living_room" | "office" | "reception" | "bathroom" | "custom";
          label: string | null;
          width: number | null;
          height: number | null;
          depth: number | null;
          length: number | null;
          ceiling_height: number | null;
          notes: string | null;
          approval_status: "draft" | "submitted" | "approved" | "needs_revision";
          approved_by: string | null;
          approved_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["measurements"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["measurements"]["Insert"]>;
      };
      measurement_attachments: {
        Row: {
          id: string;
          workspace_id: string;
          site_visit_id: string | null;
          measurement_id: string | null;
          file_url: string;
          file_name: string | null;
          file_type: "site_photo" | "measurement_photo" | "reference_image" | "notes_image" | null;
          file_size: number | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["measurement_attachments"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["measurement_attachments"]["Insert"]>;
      };
      design_briefs: {
        Row: {
          id: string;
          workspace_id: string;
          brief_number: string;
          title: string;
          sales_order_id: string | null;
          site_visit_id: string | null;
          customer_id: string | null;
          customer_name: string | null;
          assigned_designer: string | null;
          design_type: "kitchen" | "wardrobe" | "bedroom" | "living_room" | "office" | "bathroom" | "reception" | "custom";
          style: "modern" | "classic" | "minimal" | "luxury" | "neo_classic" | "industrial" | "custom" | null;
          dimensions_summary: Json;
          preferred_colors: string | null;
          preferred_materials: string | null;
          special_notes: string | null;
          status: "draft" | "in_progress" | "internal_review" | "client_review" | "revision" | "approved" | "cancelled";
          version: number;
          approved_by: string | null;
          approved_at: string | null;
          revision_notes: string | null;
          start_date: string | null;
          due_date: string | null;
          completed_date: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["design_briefs"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["design_briefs"]["Insert"]>;
      };
      design_files: {
        Row: {
          id: string;
          workspace_id: string;
          design_brief_id: string;
          file_url: string;
          file_name: string | null;
          file_type: "technical_drawing" | "3d_render" | "floor_plan" | "elevation" | "detail" | "reference" | "revision" | "client_approved" | null;
          file_format: string | null;
          file_size: number | null;
          version: number;
          notes: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["design_files"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["design_files"]["Insert"]>;
      };
      design_comments: {
        Row: {
          id: string;
          workspace_id: string;
          design_brief_id: string;
          author_name: string;
          author_role: "designer" | "manager" | "client" | "technician" | null;
          comment: string;
          comment_type: "general" | "revision_request" | "approval" | "annotation" | "question";
          resolved: boolean;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["design_comments"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["design_comments"]["Insert"]>;
      };
      production_orders: {
        Row: {
          id: string;
          workspace_id: string;
          po_number: string;
          title: string;
          sales_order_id: string | null;
          design_brief_id: string | null;
          customer_id: string | null;
          customer_name: string | null;
          assigned_station: string | null;
          assigned_workers: Json;
          priority: "critical" | "urgent" | "high" | "medium" | "low";
          start_date: string | null;
          due_date: string | null;
          completed_date: string | null;
          status: "pending" | "cutting" | "edgebanding" | "drilling" | "assembly" | "finishing" | "quality_check" | "packing" | "ready" | "delivered" | "cancelled";
          current_stage: string | null;
          progress: number;
          materials_summary: Json;
          notes: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["production_orders"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["production_orders"]["Insert"]>;
      };
      cutting_list_items: {
        Row: {
          id: string;
          workspace_id: string;
          production_order_id: string;
          piece_number: number;
          part_name: string;
          material: string | null;
          thickness: number | null;
          width: number | null;
          length: number | null;
          qty: number;
          edge_top: string | null;
          edge_bottom: string | null;
          edge_left: string | null;
          edge_right: string | null;
          grain_direction: "horizontal" | "vertical" | "none" | null;
          cnc_program: string | null;
          notes: string | null;
          completed: boolean;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["cutting_list_items"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["cutting_list_items"]["Insert"]>;
      };
      production_stage_log: {
        Row: {
          id: string;
          workspace_id: string;
          production_order_id: string;
          stage: string;
          status: "pending" | "in_progress" | "completed" | "skipped";
          started_at: string | null;
          completed_at: string | null;
          duration_minutes: number | null;
          worker_name: string | null;
          station: string | null;
          notes: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["production_stage_log"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["production_stage_log"]["Insert"]>;
      };
      qc_inspections: {
        Row: {
          id: string;
          workspace_id: string;
          inspection_number: string;
          production_order_id: string | null;
          sales_order_id: string | null;
          customer_name: string | null;
          inspector_name: string | null;
          inspection_type: "in_process" | "pre_assembly" | "final" | "pre_delivery" | "re_inspection";
          status: "pending" | "in_progress" | "passed" | "failed" | "conditional";
          checklist: Json;
          overall_score: number | null;
          result_notes: string | null;
          inspected_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["qc_inspections"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["qc_inspections"]["Insert"]>;
      };
      qc_defects: {
        Row: {
          id: string;
          workspace_id: string;
          inspection_id: string;
          defect_number: string;
          title: string;
          severity: "critical" | "major" | "minor" | "cosmetic";
          category: "dimension" | "surface" | "material" | "assembly" | "finish" | "hardware" | "edge" | "color" | "other";
          description: string | null;
          location: string | null;
          photo_url: string | null;
          status: "open" | "rework" | "re_inspected" | "accepted" | "rejected";
          rework_notes: string | null;
          reworked_by: string | null;
          reworked_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["qc_defects"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["qc_defects"]["Insert"]>;
      };
      deliveries: {
        Row: {
          id: string;
          workspace_id: string;
          delivery_number: string;
          production_order_id: string | null;
          sales_order_id: string | null;
          customer_name: string | null;
          customer_phone: string | null;
          delivery_address: string | null;
          delivery_date: string | null;
          delivery_time_slot: string | null;
          driver_name: string | null;
          vehicle_info: string | null;
          status: string;
          loading_notes: string | null;
          delivery_notes: string | null;
          recipient_name: string | null;
          recipient_phone: string | null;
          delivered_at: string | null;
          delivery_photo_url: string | null;
          num_pieces: number;
          num_packages: number;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["deliveries"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["deliveries"]["Insert"]>;
      };
      installations: {
        Row: {
          id: string;
          workspace_id: string;
          installation_number: string;
          delivery_id: string | null;
          sales_order_id: string | null;
          customer_name: string | null;
          customer_phone: string | null;
          site_address: string | null;
          scheduled_date: string | null;
          scheduled_time_slot: string | null;
          team_leader: string | null;
          team_members: unknown[];
          status: string;
          checklist: unknown[];
          snag_list: unknown[];
          completion_notes: string | null;
          customer_rating: number | null;
          customer_feedback: string | null;
          signature_url: string | null;
          started_at: string | null;
          completed_at: string | null;
          photos: unknown[];
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["installations"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["installations"]["Insert"]>;
      };
      employees: {
        Row: {
          id: string;
          workspace_id: string;
          employee_number: string;
          full_name: string;
          full_name_ar: string | null;
          phone: string | null;
          email: string | null;
          national_id: string | null;
          department: string;
          job_title: string | null;
          job_title_ar: string | null;
          employment_type: string;
          status: string;
          hire_date: string | null;
          termination_date: string | null;
          salary: number | null;
          salary_type: string;
          photo_url: string | null;
          emergency_contact: string | null;
          emergency_phone: string | null;
          address: string | null;
          skills: unknown[];
          documents: unknown[];
          notes: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["employees"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["employees"]["Insert"]>;
      };
      attendance: {
        Row: {
          id: string;
          workspace_id: string;
          employee_id: string;
          date: string;
          check_in: string | null;
          check_out: string | null;
          status: string;
          overtime_hours: number;
          notes: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["attendance"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["attendance"]["Insert"]>;
      };
      leave_requests: {
        Row: {
          id: string;
          workspace_id: string;
          employee_id: string;
          leave_type: string;
          start_date: string;
          end_date: string;
          days: number;
          reason: string | null;
          status: string;
          approved_by: string | null;
          approved_at: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["leave_requests"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["leave_requests"]["Insert"]>;
      };
      cost_entries: {
        Row: {
          id: string;
          workspace_id: string;
          sales_order_id: string | null;
          production_order_id: string | null;
          cost_type: string;
          description: string;
          quantity: number;
          unit_cost: number;
          total_cost: number;
          currency: string;
          date: string | null;
          supplier: string | null;
          notes: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["cost_entries"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["cost_entries"]["Insert"]>;
      };
      branches: {
        Row: {
          id: string;
          workspace_id: string;
          branch_code: string;
          name: string;
          name_ar: string | null;
          address: string | null;
          phone: string | null;
          manager_name: string | null;
          branch_type: string;
          is_active: boolean;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["branches"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["branches"]["Insert"]>;
      };
      material_requirements: {
        Row: {
          id: string;
          workspace_id: string;
          source_type: string;
          source_id: string;
          material_name: string;
          sku: string | null;
          quantity_required: number;
          quantity_available: number;
          quantity_reserved: number;
          quantity_to_purchase: number;
          unit: string;
          unit_cost: number;
          total_cost: number;
          status: string;
          purchase_request_id: string | null;
          inventory_item_id: string | null;
          priority: string;
          notes: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["material_requirements"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["material_requirements"]["Insert"]>;
      };
      pos_registers: {
        Row: {
          id: string;
          workspace_id: string;
          branch_id: string;
          register_code: string;
          name: string;
          name_ar: string | null;
          status: "active" | "inactive" | "maintenance";
          opened_by: string | null;
          opened_at: string | null;
          closed_at: string | null;
          float_amount: number;
          current_cash: number;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["pos_registers"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["pos_registers"]["Insert"]>;
      };
      pos_transactions: {
        Row: {
          id: string;
          workspace_id: string;
          branch_id: string;
          register_id: string;
          transaction_number: string;
          customer_id: string | null;
          customer_name: string | null;
          customer_phone: string | null;
          loyalty_card_number: string | null;
          subtotal: number;
          discount_amount: number;
          discount_percent: number;
          tax_amount: number;
          tax_rate: number;
          total: number;
          currency: string;
          payment_method: "cash" | "card" | "mobile_wallet" | "loyalty_points" | "split";
          payment_details: Record<string, unknown>;
          status: "completed" | "voided" | "refunded" | "pending";
          cashier_name: string;
          notes: string | null;
          receipt_printed: boolean;
          loyalty_points_earned: number;
          loyalty_points_redeemed: number;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["pos_transactions"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["pos_transactions"]["Insert"]>;
      };
      pos_transaction_items: {
        Row: {
          id: string;
          workspace_id: string;
          transaction_id: string;
          product_id: string | null;
          product_name: string;
          product_name_ar: string | null;
          sku: string | null;
          quantity: number;
          unit_price: number;
          discount_amount: number;
          discount_percent: number;
          total: number;
          cost_price: number;
          branch_id: string;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["pos_transaction_items"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["pos_transaction_items"]["Insert"]>;
      };
      branch_inventory: {
        Row: {
          id: string;
          workspace_id: string;
          branch_id: string;
          product_id: string;
          product_name: string;
          sku: string | null;
          quantity: number;
          reserved_quantity: number;
          reorder_level: number;
          unit_cost: number;
          unit_price: number;
          last_restocked_at: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["branch_inventory"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["branch_inventory"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
